=== dakota002/gcn-schema/gcn/circulars.schema.json
{
  "$id": "https://gcn.nasa.gov/schema/v7.2.2/gcn/circulars.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "GCN Circular",
  "description": "GCN Circulars are rapid astronomical bulletins submitted by and distributed to community members worldwide. They are used to share discoveries, observations, quantitative near-term predictions, requests for follow-up observations, or future observing plans related to high-energy, multi-messenger, and variable or transient astrophysical events. An archive of all GCN Circulars can be found at https://gcn.nasa.gov/circulars",
  "properties": {
    "eventId": {
      "type": "string",
      "description": "Event name, automatically inferred from the subject"
    },
    "eventType": {
      "type": "array",
      "items": { "type": "string" },
      "description": "Event type(s), automatically inferred from the subject"
    },
    "submitter": {
      "type": "string",
      "description": "Name, affiliation, and email address of the person who submitted the Circular, in the form `A. E. Einstein at IAS <albert.einstein@example.edu>`"
    },
    "submittedHow": {
      "enum": ["web", "email", "email-legacy", "api"],
      "description": "Specifies the method by which the user submitted the Circular"
    },
    "subject": {
      "type": "string",
      "description": "Subject line of the Circular"
    },
    "circularId": {
      "type": "number",
      "description": "Circular ID assigned to the Circular in the GCN Circulars archive. This value is unique to each published Circular and increments by 1"
    },
    "format": {
      "enum": ["text/plain", "text/markdown"],
      "description": "Format of the body text as a MIME type. See https://gcn.nasa.gov/docs/circulars/markdown for documentation on using Markdown in Circulars"
    },
    "body": { "type": "string", "description": "Body text" },
    "createdOn": {
      "type": "number",
      "description": "Date and time the Circular is accepted and published onto the GCN Circulars archive, formatted as a UNIX timestamp (milliseconds since the UNIX epoch)"
    }
  },
  "required": ["submitter", "subject", "circularId", "body", "createdOn"]
}

=== dakota002/gcn-schema/gcn/circulars.example.json
{
  "$schema": "https://gcn.nasa.gov/schema/v7.2.3/gcn/circulars.schema.json",
  "eventId": "GRB 230410A",
  "eventType": ["GRB"],
  "submitter": "Fermi GBM Team at MSFC/Fermi-GBM <do_not_reply@GIOC.nsstc.nasa.gov>",
  "submittedHow": "email-legacy",
  "subject": "GRB 230410A: Fermi GBM Final Real-time Localization",
  "circularId": 33603,
  "format": "text/plain",
  "body": "The Fermi GBM team reports the detection of a likely LONG GRB\\n\\nAt 11:26:00 UT on 10 Apr 2023, the Fermi Gamma-ray Burst Monitor (GBM) triggered and located GRB 230410A (trigger 702818765.135562 / 230410476).\\n\\nThe on-ground calculated location, using the Fermi GBM trigger data, is RA = 352.3, Dec = 22.9 (J2000 degrees, equivalent to J2000 23h 29m, 22d 53'), with a statistical uncertainty of 2.1 degrees.\\n\\nThe angle from the Fermi LAT boresight is 72.0 degrees.\\n\\nThe skymap can be found here:\\nhttps://heasarc.gsfc.nasa.gov/FTP/fermi/data/gbm/triggers/2023/bn230410476/quicklook/glg_skymap_all_bn230410476.png\\n\\nThe HEALPix FITS file, including the estimated localization systematic, can be found here:\\nhttps://heasarc.gsfc.nasa.gov/FTP/fermi/data/gbm/triggers/2023/bn230410476/quicklook/glg_healpix_all_bn230410476.fit\\n\\nThe GBM light curve can be found here:\\nhttps://heasarc.gsfc.nasa.gov/FTP/fermi/data/gbm/triggers/2023/bn230410476/quicklook/glg_lc_medres34_bn230410476.gif",
  "createdOn": 1718212589034
}
